# Generated by Django 3.1.3 on 2021-06-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210616_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='highest_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000, null=True),
        ),
    ]
