# Generated by Django 3.1.3 on 2021-06-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210616_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='bid',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='uncategorised', max_length=120),
        ),
    ]
